sudo: required

services:
  - docker

before_install:
  - docker build -t viveknum/fib-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true  viveknum/fib-test npm test


after_success:
  - docker build -t viveknum/fib-client ./client
  - docker build -t viveknum/fib-nginx ./nginx
  - docker build -t viveknum/fib-server ./server
  - docker build -t viveknum/fib-worker ./worker

  - echo "DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - echo "DOCKER_PASSWORD"
  - echo "DOCKER_ID"
  - docker push viveknum/fib-client
  - docker push viveknum/fib-nginx 
  - docker push viveknum/fib-server
  - docker push viveknum/fib-worker